# Generated by Django 4.0.4 on 2022-05-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='Group_sanguin',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='A+', max_length=3),
        ),
    ]
