# Generated by Django 4.0.4 on 2022-05-22 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_alter_categoriepermi_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 17, 20, 23, 904653)),
        ),
    ]
