# Generated by Django 4.0.4 on 2022-05-22 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_candidat_date_de_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_reussite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 18, 32, 7, 882554)),
        ),
    ]
