# Generated by Django 4.0.4 on 2022-05-23 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_candidat_date_reussite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 12, 6, 24, 40671)),
        ),
    ]
