# Generated by Django 4.0.4 on 2022-05-23 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_alter_candidat_date_de_dossier_alter_candidat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 16, 16, 6, 2453)),
        ),
    ]
