# Generated by Django 4.0.4 on 2022-05-24 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0010_alter_candidat_date_de_dossier_alter_candidat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='nom',
            field=models.CharField(choices=[('Code', 'Code'), ('Manoeuvre', 'Manoeuvre'), ('Conduite', 'Conduite')], default='session de epreuve', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 13, 57, 48, 260023)),
        ),
    ]
