# Generated by Django 4.0.4 on 2022-05-25 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0013_alter_candidat_date_de_dossier_alter_epreuve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 16, 22, 40, 143953)),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
