# Generated by Django 4.0.4 on 2022-06-01 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0020_rename_gerant_autoecole_gérant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 13, 12, 11, 771439)),
        ),
    ]
